// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: proto/shop/v1/orders.proto

package shopv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_PLACED      Status = 1
	Status_STATUS_PAID        Status = 2
	Status_STATUS_SHIPPED     Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_PLACED",
		2: "STATUS_PAID",
		3: "STATUS_SHIPPED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_PLACED":      1,
		"STATUS_PAID":        2,
		"STATUS_SHIPPED":     3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_shop_v1_orders_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_shop_v1_orders_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_shop_v1_orders_proto_rawDescGZIP(), []int{0}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_shop_v1_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_v1_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_shop_v1_orders_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Items         []*LineItem            `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Total         string                 `protobuf:"bytes,4,opt,name=total,proto3" json:"total,omitempty"`
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=shop.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_shop_v1_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_v1_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_shop_v1_orders_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Order) GetItems() []*LineItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *Order) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

type LineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty           int64                  `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LineItem) Reset() {
	*x = LineItem{}
	mi := &file_proto_shop_v1_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineItem) ProtoMessage() {}

func (x *LineItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_v1_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineItem.ProtoReflect.Descriptor instead.
func (*LineItem) Descriptor() ([]byte, []int) {
	return file_proto_shop_v1_orders_proto_rawDescGZIP(), []int{2}
}

func (x *LineItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *LineItem) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *LineItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

var File_proto_shop_v1_orders_proto protoreflect.FileDescriptor

const file_proto_shop_v1_orders_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/shop/v1/orders.proto\x12\ashop.v1\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x95\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12'\n" +
	"\x05items\x18\x03 \x03(\v2\x11.shop.v1.LineItemR\x05items\x12\x14\n" +
	"\x05total\x18\x04 \x01(\tR\x05total\x12'\n" +
	"\x06status\x18\x05 \x01(\x0e2\x0f.shop.v1.StatusR\x06status\"D\n" +
	"\bLineItem\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x10\n" +
	"\x03qty\x18\x02 \x01(\x03R\x03qty\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price*X\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_PLACED\x10\x01\x12\x0f\n" +
	"\vSTATUS_PAID\x10\x02\x12\x12\n" +
	"\x0eSTATUS_SHIPPED\x10\x032d\n" +
	"\x06Orders\x12*\n" +
	"\x03Get\x12\x13.shop.v1.GetRequest\x1a\x0e.shop.v1.Order\x12.\n" +
	"\x05Watch\x12\x13.shop.v1.GetRequest\x1a\x0e.shop.v1.Order0\x01B'Z%example.com/shop/proto/shop/v1;shopv1b\x06proto3"

var (
	file_proto_shop_v1_orders_proto_rawDescOnce sync.Once
	file_proto_shop_v1_orders_proto_rawDescData []byte
)

func file_proto_shop_v1_orders_proto_rawDescGZIP() []byte {
	file_proto_shop_v1_orders_proto_rawDescOnce.Do(func() {
		file_proto_shop_v1_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shop_v1_orders_proto_rawDesc), len(file_proto_shop_v1_orders_proto_rawDesc)))
	})
	return file_proto_shop_v1_orders_proto_rawDescData
}

var file_proto_shop_v1_orders_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_shop_v1_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_shop_v1_orders_proto_goTypes = []any{
	(Status)(0),        // 0: shop.v1.Status
	(*GetRequest)(nil), // 1: shop.v1.GetRequest
	(*Order)(nil),      // 2: shop.v1.Order
	(*LineItem)(nil),   // 3: shop.v1.LineItem
}
var file_proto_shop_v1_orders_proto_depIdxs = []int32{
	3, // 0: shop.v1.Order.items:type_name -> shop.v1.LineItem
	0, // 1: shop.v1.Order.status:type_name -> shop.v1.Status
	1, // 2: shop.v1.Orders.Get:input_type -> shop.v1.GetRequest
	1, // 3: shop.v1.Orders.Watch:input_type -> shop.v1.GetRequest
	2, // 4: shop.v1.Orders.Get:output_type -> shop.v1.Order
	2, // 5: shop.v1.Orders.Watch:output_type -> shop.v1.Order
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_shop_v1_orders_proto_init() }
func file_proto_shop_v1_orders_proto_init() {
	if File_proto_shop_v1_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shop_v1_orders_proto_rawDesc), len(file_proto_shop_v1_orders_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shop_v1_orders_proto_goTypes,
		DependencyIndexes: file_proto_shop_v1_orders_proto_depIdxs,
		EnumInfos:         file_proto_shop_v1_orders_proto_enumTypes,
		MessageInfos:      file_proto_shop_v1_orders_proto_msgTypes,
	}.Build()
	File_proto_shop_v1_orders_proto = out.File
	file_proto_shop_v1_orders_proto_goTypes = nil
	file_proto_shop_v1_orders_proto_depIdxs = nil
}
