package docgen

import (
	"strings"
	"testing"
)

// TestTheReadmeIsSplicedAndNothingElse: every generated block is replaced
// between its markers, a block's own markers survive to be replaced again,
// and every byte outside them is left as it was.
func TestTheReadmeIsSplicedAndNothingElse(t *testing.T) {
	root := t.TempDir()
	write(t, root, "site/sessions/tour.out", FormatTranscript([]Entry{
		{In: ":t x", Out: "int"},
		{In: ":since", Out: "one\ntwo\nthree\nfour", Clip: 1, View: true},
	}))
	write(t, root, "README.md", strings.Join([]string{
		"# title, kept",
		"<!-- gluon:session tour -->",
		"stale",
		"<!-- gluon:end -->",
		"between, kept",
		"<!-- gluon:help:start -->",
		"stale help",
		"<!-- gluon:help:end -->",
		"<!-- gluon:guides -->",
		"<!-- gluon:end -->",
		"end, kept",
		"",
	}, "\n"))
	m := Model{
		Site: Site{BaseURL: "https://example.test/"},
		Pages: []Page{
			{Path: "guide/index.html", Title: "Guides", Section: "Guides"},
			{Path: "guide/start.html", Title: "Start", Lead: "the first one", Section: "Guides"},
			{Path: "reference/index.html", Title: "Reference", Section: "Reference"},
		},
		Reg: Registry{HelpText: "  :t <exp>  the type"},
	}
	got, err := spliceReadme(m, root)
	if err != nil {
		t.Fatal(err)
	}
	want := strings.Join([]string{
		"# title, kept",
		"<!-- gluon:session tour -->",
		"```",
		"gluon> :t x",
		"int",
		"gluon> :since",
		"one",
		"… 3 more lines",
		"```",
		"<!-- gluon:end -->",
		"between, kept",
		"<!-- gluon:help:start -->",
		"<!-- generated by `just docs` from the command registry: edit the registry, not this -->",
		"```",
		"  :t <exp>  the type",
		"```",
		"<!-- gluon:help:end -->",
		"<!-- gluon:guides -->",
		"- **[Start](https://example.test/guide/start.html)** — the first one",
		"<!-- gluon:end -->",
		"end, kept",
		"",
	}, "\n")
	if string(got) != want {
		t.Errorf("spliced:\n%s\nwant:\n%s", got, want)
	}

	// Spliced again, it is the same: the markers are where they were.
	write(t, root, "README.md", string(got))
	if again, err := spliceReadme(m, root); err != nil || string(again) != want {
		t.Errorf("a second splice changed the README (%v):\n%s", err, again)
	}
}

// TestReadmeLinksLandOnPages: the README's links into the site are absolute,
// so Check does not follow them and CheckReadme does.
func TestReadmeLinksLandOnPages(t *testing.T) {
	files := map[string][]byte{
		"docs/index.html":       []byte(`<!doctype html><html><body><p id="top">x</p></body></html>`),
		"docs/guide/start.html": []byte(`<!doctype html><html><body><h2 id="install">x</h2></body></html>`),
	}
	readme := []byte(strings.Join([]string{
		"[home](https://example.test/)",
		"[start](https://example.test/guide/start.html#install)",
		"[gone](https://example.test/guide/nothing.html)",
		"[no id](https://example.test/guide/start.html#nowhere)",
		"[elsewhere](https://go.dev/doc/)",
	}, "\n"))
	errs := CheckReadme(readme, "https://example.test/", files)
	if len(errs) != 2 || !strings.Contains(errs[0], "nothing.html") || !strings.Contains(errs[1], "#nowhere") {
		t.Errorf("errors = %q, want the missing page and the missing id", errs)
	}
}
