package inspect

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/types"
	"strings"
	"unicode"
)

// A mock is a method set with the bodies left out, which makes it the one kind
// of code generation gluon can do with no execution at all: types.NewMethodSet
// is the same computation :m runs, and it already carries promoted methods, so
// an interface that embeds another needs no separate walk.
//
// Two decisions are load-bearing in what comes out.
//
// An unset function field panics naming its method. Returning the zero values
// instead is how a mock produces a test that passes for the wrong reason — the
// assertion holds because nothing was called, and nothing says so. A panic
// naming the method is what a hand-written mock does, and it is the only
// behaviour that cannot be mistaken for a real result.
//
// The spy records arguments rather than counting calls into a separate field.
// The count is len(Calls), so a Count() method reads it back without a second
// piece of state that could disagree with the first.

// Mock renders a type implementing in. iface is the interface as the user
// named it — io.ReadWriter — which is both what the doc comment says it
// implements and where the generated type's name comes from: ReadWriterMock,
// or ReadWriterSpy when spy is set and each method also records what it was
// called with.
//
// The name has to be carried in rather than read back off in, because an
// interface's *types.Interface is its method set with the name already gone:
// TypeString would render io.ReadWriter as interface{io.Reader; io.Writer}.
//
// pkg is the session's own package, so a type it declared is spelled bare and
// everything else keeps its qualifier — the same rule :t prints under.
func Mock(pkg *types.Package, iface string, in *types.Interface, spy bool) (string, error) {
	q := qualifier(pkg)
	base := baseName(iface)
	name := base + "Mock"
	kind := "mock"
	if spy {
		name, kind = base+"Spy", "spy"
	}

	ms := types.NewMethodSet(in)
	if ms.Len() == 0 {
		return "", fmt.Errorf("%s has no methods — every type already implements it, so there is nothing to mock", iface)
	}

	methods := make([]mockMethod, 0, ms.Len())
	for i := range ms.Len() {
		fn, ok := ms.At(i).Obj().(*types.Func)
		if !ok {
			continue
		}
		sig, ok := fn.Type().(*types.Signature)
		if !ok {
			continue
		}
		// An unexported method belongs to the package that declared it, and no
		// type outside that package can supply one. Emitting the field anyway
		// would produce source that reads right and does not compile.
		if !ast.IsExported(fn.Name()) && fn.Pkg() != pkg {
			return "", fmt.Errorf("%s requires %s.%s, which is unexported — only %s can implement it",
				iface, fn.Pkg().Name(), fn.Name(), fn.Pkg().Name())
		}
		methods = append(methods, newMockMethod(fn.Name(), sig, q))
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// %s is a %s implementation of %s, generated by gluon.\n", name, kind, iface)
	b.WriteString("// A method whose function field is unset panics naming itself, so an\n")
	b.WriteString("// expectation nobody set cannot be mistaken for a real result.\n")
	fmt.Fprintf(&b, "type %s struct {\n", name)
	for _, m := range methods {
		fmt.Fprintf(&b, "\t%sFunc func(%s)%s\n", m.Name, m.Params, m.Results)
		if spy {
			fmt.Fprintf(&b, "\t// %sCalls holds one entry per call, in order.\n", m.Name)
			fmt.Fprintf(&b, "\t%sCalls []%s\n", m.Name, m.CallStruct)
		}
	}
	b.WriteString("}\n")

	for _, m := range methods {
		b.WriteString("\n")
		fmt.Fprintf(&b, "func (m *%s) %s(%s)%s {\n", name, m.Name, m.Params, m.Results)
		if spy {
			fmt.Fprintf(&b, "\tm.%sCalls = append(m.%sCalls, %s{%s})\n",
				m.Name, m.Name, m.CallStruct, strings.Join(m.Args, ", "))
		}
		fmt.Fprintf(&b, "\tif m.%sFunc == nil {\n", m.Name)
		fmt.Fprintf(&b, "\t\tpanic(%q)\n", name+"."+m.Name+" was called with no "+m.Name+"Func set")
		b.WriteString("\t}\n")
		call := fmt.Sprintf("m.%sFunc(%s)", m.Name, strings.Join(m.Pass, ", "))
		if m.Results == "" {
			fmt.Fprintf(&b, "\t%s\n", call)
		} else {
			fmt.Fprintf(&b, "\treturn %s\n", call)
		}
		b.WriteString("}\n")

		if spy {
			b.WriteString("\n")
			fmt.Fprintf(&b, "// %sCount is how many times %s was called.\n", m.Name, m.Name)
			fmt.Fprintf(&b, "func (m *%s) %sCount() int { return len(m.%sCalls) }\n", name, m.Name, m.Name)
		}
	}

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		// Generated source that will not even parse is a bug here, not
		// something for the user to work around; saying so beats printing it.
		return "", fmt.Errorf("generated source did not format: %w", err)
	}
	return string(src), nil
}

// mockMethod is one method, in the four forms the templates above need.
type mockMethod struct {
	Name string
	// Params is the parameter list as it is declared, names included.
	Params string
	// Results is the result list, with its leading space, or "".
	Results string
	// Pass is the parameter names as they are forwarded, with the variadic
	// last one carrying its ellipsis.
	Pass []string
	// Args is the same names without the ellipsis, for the recorded call.
	Args []string
	// CallStruct is the type one recorded call is held as: a struct with one
	// exported field per parameter, or the empty struct for a method that
	// takes none — which still records that it was called.
	CallStruct string
}

func newMockMethod(name string, sig *types.Signature, q types.Qualifier) mockMethod {
	m := mockMethod{Name: name}
	params := sig.Params()
	names := paramNames(params)

	var decls, fields []string
	seenField := map[string]bool{}
	for i, n := range names {
		v := params.At(i)
		t := types.TypeString(v.Type(), q)
		pass, field := n, t
		if sig.Variadic() && i == params.Len()-1 {
			// The declaration spells the variadic element type; the field
			// holding what was passed keeps the slice it actually is.
			if s, ok := v.Type().(*types.Slice); ok {
				t = "..." + types.TypeString(s.Elem(), q)
			}
			pass = n + "..."
		}
		fn := exportedField(n, i)
		if seenField[fn] {
			// `x` and `X` are two parameters and one field name; the second
			// one falls back to its position rather than shadowing the first.
			fn = fmt.Sprintf("A%d", i)
		}
		seenField[fn] = true
		decls = append(decls, n+" "+t)
		fields = append(fields, "\t\t"+fn+" "+field+"\n")
		m.Pass = append(m.Pass, pass)
		m.Args = append(m.Args, n)
	}
	m.Params = strings.Join(decls, ", ")
	m.CallStruct = "struct{}"
	if len(fields) > 0 {
		m.CallStruct = "struct {\n" + strings.Join(fields, "") + "\t}"
	}

	res := sig.Results()
	switch res.Len() {
	case 0:
	case 1:
		m.Results = " " + types.TypeString(res.At(0).Type(), q)
	default:
		parts := make([]string, 0, res.Len())
		for i := range res.Len() {
			parts = append(parts, types.TypeString(res.At(i).Type(), q))
		}
		m.Results = " (" + strings.Join(parts, ", ") + ")"
	}
	return m
}

// paramNames gives every parameter a usable identifier. An interface method
// may declare none at all, and a blank one cannot be forwarded, so both become
// positional — and a name that would shadow the receiver is moved aside.
func paramNames(params *types.Tuple) []string {
	seen := map[string]bool{"m": true}
	out := make([]string, params.Len())
	for i := range params.Len() {
		n := params.At(i).Name()
		if n == "" || n == "_" || seen[n] {
			n = fmt.Sprintf("a%d", i)
		}
		seen[n] = true
		out[i] = n
	}
	return out
}

// exportedField is a parameter's name as a struct field. The recorded call is
// read from wherever the mock is used, so the fields have to be exported.
func exportedField(name string, i int) string {
	r := []rune(name)
	r[0] = unicode.ToUpper(r[0])
	f := string(r)
	if !ast.IsExported(f) {
		// An identifier that will not capitalise — one leading with an
		// underscore or a non-cased rune — falls back to its position.
		return fmt.Sprintf("A%d", i)
	}
	return f
}

// baseName is the identifier part of an interface's name: ReadWriter from
// io.ReadWriter. A name that is not an identifier at all — an interface
// literal — leaves the generated type named for what it is and nothing else.
func baseName(iface string) string {
	if i := strings.LastIndex(iface, "."); i >= 0 {
		iface = iface[i+1:]
	}
	if !isIdent(iface) {
		return ""
	}
	return iface
}

func isIdent(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		if r == '_' || unicode.IsLetter(r) || (i > 0 && unicode.IsDigit(r)) {
			continue
		}
		return false
	}
	return true
}
