// probe.proto is the surface :grpc's integration tests are written against.
//
// It is deliberately small and deliberately mixed: one unary method for the
// ordinary path, one that fails, one whose answer changes on every call, and
// the three streaming shapes so that listing and refusing them is testable
// against a real server rather than against a stub.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: probe.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Text  string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// meta_key names a metadata key the server should read back, which is how a
	// credential that reaches the wire becomes visible to a test.
	MetaKey       string `protobuf:"bytes,2,opt,name=meta_key,json=metaKey,proto3" json:"meta_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_probe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_probe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_probe_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EchoRequest) GetMetaKey() string {
	if x != nil {
		return x.MetaKey
	}
	return ""
}

type EchoReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Text  string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Meta  string                 `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	// count increments on every call the process serves, so two calls that
	// returned the same number came from one cached answer.
	Count int64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	// conn identifies the connection the call arrived on.
	Conn string `protobuf:"bytes,4,opt,name=conn,proto3" json:"conn,omitempty"`
	// took exists to put a google.protobuf.Duration in a response, so that a
	// field with a registered renderer can be shown to render through it.
	Took          *durationpb.Duration `protobuf:"bytes,5,opt,name=took,proto3" json:"took,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoReply) Reset() {
	*x = EchoReply{}
	mi := &file_probe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoReply) ProtoMessage() {}

func (x *EchoReply) ProtoReflect() protoreflect.Message {
	mi := &file_probe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoReply.ProtoReflect.Descriptor instead.
func (*EchoReply) Descriptor() ([]byte, []int) {
	return file_probe_proto_rawDescGZIP(), []int{1}
}

func (x *EchoReply) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EchoReply) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *EchoReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *EchoReply) GetConn() string {
	if x != nil {
		return x.Conn
	}
	return ""
}

func (x *EchoReply) GetTook() *durationpb.Duration {
	if x != nil {
		return x.Took
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_probe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_probe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_probe_proto_rawDescGZIP(), []int{2}
}

var File_probe_proto protoreflect.FileDescriptor

const file_probe_proto_rawDesc = "" +
	"\n" +
	"\vprobe.proto\x12\tgluontest\x1a\x1egoogle/protobuf/duration.proto\"<\n" +
	"\vEchoRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\bmeta_key\x18\x02 \x01(\tR\ametaKey\"\x8c\x01\n" +
	"\tEchoReply\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04meta\x18\x02 \x01(\tR\x04meta\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x12\x12\n" +
	"\x04conn\x18\x04 \x01(\tR\x04conn\x12-\n" +
	"\x04took\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x04took\"\a\n" +
	"\x05Empty2\x90\x02\n" +
	"\x05Probe\x124\n" +
	"\x04Echo\x12\x16.gluontest.EchoRequest\x1a\x14.gluontest.EchoReply\x12*\n" +
	"\x04Fail\x12\x10.gluontest.Empty\x1a\x10.gluontest.Empty\x121\n" +
	"\x05Watch\x12\x10.gluontest.Empty\x1a\x14.gluontest.EchoReply0\x01\x128\n" +
	"\x06Upload\x12\x16.gluontest.EchoRequest\x1a\x14.gluontest.EchoReply(\x01\x128\n" +
	"\x04Chat\x12\x16.gluontest.EchoRequest\x1a\x14.gluontest.EchoReply(\x010\x01B\x1eZ\x1cgluon.test/grpcserver/testpbb\x06proto3"

var (
	file_probe_proto_rawDescOnce sync.Once
	file_probe_proto_rawDescData []byte
)

func file_probe_proto_rawDescGZIP() []byte {
	file_probe_proto_rawDescOnce.Do(func() {
		file_probe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_probe_proto_rawDesc), len(file_probe_proto_rawDesc)))
	})
	return file_probe_proto_rawDescData
}

var file_probe_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_probe_proto_goTypes = []any{
	(*EchoRequest)(nil),         // 0: gluontest.EchoRequest
	(*EchoReply)(nil),           // 1: gluontest.EchoReply
	(*Empty)(nil),               // 2: gluontest.Empty
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_probe_proto_depIdxs = []int32{
	3, // 0: gluontest.EchoReply.took:type_name -> google.protobuf.Duration
	0, // 1: gluontest.Probe.Echo:input_type -> gluontest.EchoRequest
	2, // 2: gluontest.Probe.Fail:input_type -> gluontest.Empty
	2, // 3: gluontest.Probe.Watch:input_type -> gluontest.Empty
	0, // 4: gluontest.Probe.Upload:input_type -> gluontest.EchoRequest
	0, // 5: gluontest.Probe.Chat:input_type -> gluontest.EchoRequest
	1, // 6: gluontest.Probe.Echo:output_type -> gluontest.EchoReply
	2, // 7: gluontest.Probe.Fail:output_type -> gluontest.Empty
	1, // 8: gluontest.Probe.Watch:output_type -> gluontest.EchoReply
	1, // 9: gluontest.Probe.Upload:output_type -> gluontest.EchoReply
	1, // 10: gluontest.Probe.Chat:output_type -> gluontest.EchoReply
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_probe_proto_init() }
func file_probe_proto_init() {
	if File_probe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_probe_proto_rawDesc), len(file_probe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_probe_proto_goTypes,
		DependencyIndexes: file_probe_proto_depIdxs,
		MessageInfos:      file_probe_proto_msgTypes,
	}.Build()
	File_probe_proto = out.File
	file_probe_proto_goTypes = nil
	file_probe_proto_depIdxs = nil
}
