// probe.proto is the surface :grpc's integration tests are written against.
//
// It is deliberately small and deliberately mixed: one unary method for the
// ordinary path, one that fails, one whose answer changes on every call, and
// the three streaming shapes so that listing and refusing them is testable
// against a real server rather than against a stub.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.36.0
// source: probe.proto

package testpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Probe_Echo_FullMethodName   = "/gluontest.Probe/Echo"
	Probe_Fail_FullMethodName   = "/gluontest.Probe/Fail"
	Probe_Watch_FullMethodName  = "/gluontest.Probe/Watch"
	Probe_Upload_FullMethodName = "/gluontest.Probe/Upload"
	Probe_Chat_FullMethodName   = "/gluontest.Probe/Chat"
)

// ProbeClient is the client API for Probe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProbeClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoReply, error)
	Fail(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Watch(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EchoReply], error)
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EchoRequest, EchoReply], error)
	Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EchoRequest, EchoReply], error)
}

type probeClient struct {
	cc grpc.ClientConnInterface
}

func NewProbeClient(cc grpc.ClientConnInterface) ProbeClient {
	return &probeClient{cc}
}

func (c *probeClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoReply)
	err := c.cc.Invoke(ctx, Probe_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *probeClient) Fail(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Probe_Fail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *probeClient) Watch(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EchoReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Probe_ServiceDesc.Streams[0], Probe_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, EchoReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Probe_WatchClient = grpc.ServerStreamingClient[EchoReply]

func (c *probeClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EchoRequest, EchoReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Probe_ServiceDesc.Streams[1], Probe_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EchoRequest, EchoReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Probe_UploadClient = grpc.ClientStreamingClient[EchoRequest, EchoReply]

func (c *probeClient) Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EchoRequest, EchoReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Probe_ServiceDesc.Streams[2], Probe_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EchoRequest, EchoReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Probe_ChatClient = grpc.BidiStreamingClient[EchoRequest, EchoReply]

// ProbeServer is the server API for Probe service.
// All implementations must embed UnimplementedProbeServer
// for forward compatibility.
type ProbeServer interface {
	Echo(context.Context, *EchoRequest) (*EchoReply, error)
	Fail(context.Context, *Empty) (*Empty, error)
	Watch(*Empty, grpc.ServerStreamingServer[EchoReply]) error
	Upload(grpc.ClientStreamingServer[EchoRequest, EchoReply]) error
	Chat(grpc.BidiStreamingServer[EchoRequest, EchoReply]) error
	mustEmbedUnimplementedProbeServer()
}

// UnimplementedProbeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProbeServer struct{}

func (UnimplementedProbeServer) Echo(context.Context, *EchoRequest) (*EchoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedProbeServer) Fail(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Fail not implemented")
}
func (UnimplementedProbeServer) Watch(*Empty, grpc.ServerStreamingServer[EchoReply]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedProbeServer) Upload(grpc.ClientStreamingServer[EchoRequest, EchoReply]) error {
	return status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedProbeServer) Chat(grpc.BidiStreamingServer[EchoRequest, EchoReply]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedProbeServer) mustEmbedUnimplementedProbeServer() {}
func (UnimplementedProbeServer) testEmbeddedByValue()               {}

// UnsafeProbeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProbeServer will
// result in compilation errors.
type UnsafeProbeServer interface {
	mustEmbedUnimplementedProbeServer()
}

func RegisterProbeServer(s grpc.ServiceRegistrar, srv ProbeServer) {
	// If the following call panics, it indicates UnimplementedProbeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Probe_ServiceDesc, srv)
}

func _Probe_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Probe_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Probe_Fail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeServer).Fail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Probe_Fail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeServer).Fail(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Probe_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProbeServer).Watch(m, &grpc.GenericServerStream[Empty, EchoReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Probe_WatchServer = grpc.ServerStreamingServer[EchoReply]

func _Probe_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProbeServer).Upload(&grpc.GenericServerStream[EchoRequest, EchoReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Probe_UploadServer = grpc.ClientStreamingServer[EchoRequest, EchoReply]

func _Probe_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProbeServer).Chat(&grpc.GenericServerStream[EchoRequest, EchoReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Probe_ChatServer = grpc.BidiStreamingServer[EchoRequest, EchoReply]

// Probe_ServiceDesc is the grpc.ServiceDesc for Probe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Probe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gluontest.Probe",
	HandlerType: (*ProbeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Probe_Echo_Handler,
		},
		{
			MethodName: "Fail",
			Handler:    _Probe_Fail_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Probe_Watch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Upload",
			Handler:       _Probe_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Chat",
			Handler:       _Probe_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "probe.proto",
}
